import * as admin from 'firebase-admin';
import { readFileSync } from 'fs';
import { resolve } from 'path';

const credentialsPath = resolve(__dirname, 'src/serviceAccountKey.json');
const credentials = JSON.parse(readFileSync(credentialsPath, 'utf-8'));
admin.initializeApp({
  credential: admin.credential.cert(credentials),
  projectId: 'sppd-psbtph',
});

const db = admin.firestore();

async function seed() {
  const now = new Date();
  const data = [
    {
      Tahun_Kegiatan: '2026',
      Kode_Kegiatan: 'KGT-001',
      Nama_Pegawai: 'Anisa anggun Fadelia',
      NIP_Pegawai: '199001012015032001',
      Pangkat_dan_Golongan: 'Penata Muda (III/a)',
      Jabatan_Pegawai: 'Analis Keuangan',
      Tingkat_Menurut_Peraturan: 'Luar Kota',
      Maksud_Perjalanan_Dinas: 'Rapat Koordinasi Keuangan Daerah',
      Berangkat_dari: 'Kantor Pusat',
      Tujuan: 'Kantor Gubernur',
      Tanggal_Berangkat: admin.firestore.Timestamp.fromDate(new Date('2026-01-15')),
      Tanggal_Kembali: admin.firestore.Timestamp.fromDate(new Date('2026-01-16')),
      Pada_tanggal: admin.firestore.Timestamp.fromDate(new Date('2026-01-10')),
      Kegiatan: 'Rapat',
      Kategori_DL: 'Pendek',
      Alat_Angkutan: 'Pesawat',
      Nama_Produsen: 'Budi Santoso',
      Jabatan_Produsen: 'Kepala Bidang Keuangan',
      NIP_Produsen: '198501012010011001',
      Nomor_SPT: 'SPT/2026/001',
      No_Urut_SPPD: 1,
      Bulan_Kegiatan: 'I',
      Jumlah_Uang: 2500000,
      Terbilang: 'Dua Juta Lima Ratus Ribu Rupiah',
      wilayah_kerja: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      Tahun_Kegiatan: '2026',
      Kode_Kegiatan: 'KGT-002',
      Nama_Pegawai: 'Budi Santoso',
      NIP_Pegawai: '198501012010011001',
      Pangkat_dan_Golongan: 'Penata (III/b)',
      Jabatan_Pegawai: 'Kepala Bidang Keuangan',
      Tingkat_Menurut_Peraturan: 'Luar Kota',
      Maksud_Perjalanan_Dinas: 'Audit Keuangan Daerah',
      Berangkat_dari: 'Kantor Pusat',
      Tujuan: 'Kabupaten A',
      Tanggal_Berangkat: admin.firestore.Timestamp.fromDate(new Date('2026-02-10')),
      Tanggal_Kembali: admin.firestore.Timestamp.fromDate(new Date('2026-02-12')),
      Pada_tanggal: admin.firestore.Timestamp.fromDate(new Date('2026-02-05')),
      Kegiatan: 'Audit',
      Kategori_DL: 'Sedang',
      Alat_Angkutan: 'Pesawat',
      Nama_Produsen: 'Anisa anggun Fadelia',
      Jabatan_Produsen: 'Analis Keuangan',
      NIP_Produsen: '199001012015032001',
      Nomor_SPT: 'SPT/2026/002',
      No_Urut_SPPD: 2,
      Bulan_Kegiatan: 'II',
      Jumlah_Uang: 5000000,
      Terbilang: 'Lima Juta Rupiah',
      wilayah_kerja: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      Tahun_Kegiatan: '2026',
      Kode_Kegiatan: 'KGT-003',
      Nama_Pegawai: 'Citra Dewi',
      NIP_Pegawai: '199203012018032002',
      Pangkat_dan_Golongan: 'Penata Muda Tingkat I (III/b)',
      Jabatan_Pegawai: 'Pemeriksa Keuangan',
      Tingkat_Menurut_Peraturan: 'Luar Kota',
      Maksud_Perjalanan_Dinas: 'Verifikasi Laporan Keuangan',
      Berangkat_dari: 'Kantor Pusat',
      Tujuan: 'Kota B',
      Tanggal_Berangkat: admin.firestore.Timestamp.fromDate(new Date('2026-03-05')),
      Tanggal_Kembali: admin.firestore.Timestamp.fromDate(new Date('2026-03-07')),
      Pada_tanggal: admin.firestore.Timestamp.fromDate(new Date('2026-03-01')),
      Kegiatan: 'Verifikasi',
      Kategori_DL: 'Pendek',
      Alat_Angkutan: 'Kereta Api',
      Nama_Produsen: 'Budi Santoso',
      Jabatan_Produsen: 'Kepala Bidang Keuangan',
      NIP_Produsen: '198501012010011001',
      Nomor_SPT: 'SPT/2026/003',
      No_Urut_SPPD: 3,
      Bulan_Kegiatan: 'III',
      Jumlah_Uang: 3000000,
      Terbilang: 'Tiga Juta Rupiah',
      wilayah_kerja: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      Tahun_Kegiatan: '2026',
      Kode_Kegiatan: 'KGT-004',
      Nama_Pegawai: 'Dedi Prasetyo',
      NIP_Pegawai: '198807152012011003',
      Pangkat_dan_Golongan: 'Penata (III/c)',
      Jabatan_Pegawai: 'Kepala Sub Bagian Perbendaharaan',
      Tingkat_Menurut_Peraturan: 'Luar Kota',
      Maksud_Perjalanan_Dinas: 'Sosialisasi Peraturan Perbendaharaan',
      Berangkat_dari: 'Kantor Pusat',
      Tujuan: 'Kabupaten C',
      Tanggal_Berangkat: admin.firestore.Timestamp.fromDate(new Date('2026-04-10')),
      Tanggal_Kembali: admin.firestore.Timestamp.fromDate(new Date('2026-04-11')),
      Pada_tanggal: admin.firestore.Timestamp.fromDate(new Date('2026-04-05')),
      Kegiatan: 'Sosialisasi',
      Kategori_DL: 'Pendek',
      Alat_Angkutan: 'Mobil Dinas',
      Nama_Produsen: 'Anisa anggun Fadelia',
      Jabatan_Produsen: 'Analis Keuangan',
      NIP_Produsen: '199001012015032001',
      Nomor_SPT: 'SPT/2026/004',
      No_Urut_SPPD: 4,
      Bulan_Kegiatan: 'IV',
      Jumlah_Uang: 1500000,
      Terbilang: 'Satu Juta Lima Ratus Ribu Rupiah',
      wilayah_kerja: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      Tahun_Kegiatan: '2026',
      Kode_Kegiatan: 'KGT-005',
      Nama_Pegawai: 'Eka Putri',
      NIP_Pegawai: '199511202020032004',
      Pangkat_dan_Golongan: 'Pengatur Muda Tingkat I (II/b)',
      Jabatan_Pegawai: 'Bendahara Pengeluaran',
      Tingkat_Menurut_Peraturan: 'Luar Kota',
      Maksud_Perjalanan_Dinas: 'Pembayaran Gaji Pegawai',
      Berangkat_dari: 'Kantor Pusat',
      Tujuan: 'Bank Daerah',
      Tanggal_Berangkat: admin.firestore.Timestamp.fromDate(new Date('2026-05-15')),
      Tanggal_Kembali: admin.firestore.Timestamp.fromDate(new Date('2026-05-15')),
      Pada_tanggal: admin.firestore.Timestamp.fromDate(new Date('2026-05-10')),
      Kegiatan: 'Lainnya',
      Kategori_DL: 'Pendek',
      Alat_Angkutan: 'Mobil Dinas',
      Nama_Produsen: 'Budi Santoso',
      Jabatan_Produsen: 'Kepala Bidang Keuangan',
      NIP_Produsen: '198501012010011001',
      Nomor_SPT: 'SPT/2026/005',
      No_Urut_SPPD: 5,
      Bulan_Kegiatan: 'V',
      Jumlah_Uang: 10000000,
      Terbilang: 'Sepuluh Juta Rupiah',
      wilayah_kerja: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      Tahun_Kegiatan: '2026',
      Kode_Kegiatan: 'KGT-006',
      Nama_Pegawai: 'Fajar Nugroho',
      NIP_Pegawai: '198309101990031005',
      Pangkat_dan_Golongan: 'Pembina (IV/a)',
      Jabatan_Pegawai: 'Kepala Badan Keuangan Daerah',
      Tingkat_Menurut_Peraturan: 'Luar Kota',
      Maksud_Perjalanan_Dinas: 'Rapat Kerja Nasional',
      Berangkat_dari: 'Kantor Pusat',
      Tujuan: 'Jakarta',
      Tanggal_Berangkat: admin.firestore.Timestamp.fromDate(new Date('2026-06-20')),
      Tanggal_Kembali: admin.firestore.Timestamp.fromDate(new Date('2026-06-22')),
      Pada_tanggal: admin.firestore.Timestamp.fromDate(new Date('2026-06-15')),
      Kegiatan: 'Rapat',
      Kategori_DL: 'Sedang',
      Alat_Angkutan: 'Pesawat',
      Nama_Produsen: 'Anisa anggun Fadelia',
      Jabatan_Produsen: 'Analis Keuangan',
      NIP_Produsen: '199001012015032001',
      Nomor_SPT: 'SPT/2026/006',
      No_Urut_SPPD: 6,
      Bulan_Kegiatan: 'VI',
      Jumlah_Uang: 7500000,
      Terbilang: 'Tujuh Juta Lima Ratus Ribu Rupiah',
      wilayah_kerja: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      Tahun_Kegiatan: '2026',
      Kode_Kegiatan: 'KGT-007',
      Nama_Pegawai: 'Gita Sari',
      NIP_Pegawai: '199304252019032006',
      Pangkat_dan_Golongan: 'Penata Muda (III/a)',
      Jabatan_Pegawai: 'Analis Anggaran',
      Tingkat_Menurut_Peraturan: 'Luar Kota',
      Maksud_Perjalanan_Dinas: 'Penyusunan APBD',
      Berangkat_dari: 'Kantor Pusat',
      Tujuan: 'Kantor DPRD',
      Tanggal_Berangkat: admin.firestore.Timestamp.fromDate(new Date('2026-07-05')),
      Tanggal_Kembali: admin.firestore.Timestamp.fromDate(new Date('2026-07-06')),
      Pada_tanggal: admin.firestore.Timestamp.fromDate(new Date('2026-07-01')),
      Kegiatan: 'Rapat',
      Kategori_DL: 'Pendek',
      Alat_Angkutan: 'Mobil Dinas',
      Nama_Produsen: 'Budi Santoso',
      Jabatan_Produsen: 'Kepala Bidang Keuangan',
      NIP_Produsen: '198501012010011001',
      Nomor_SPT: 'SPT/2026/007',
      No_Urut_SPPD: 7,
      Bulan_Kegiatan: 'VII',
      Jumlah_Uang: 2000000,
      Terbilang: 'Dua Juta Rupiah',
      wilayah_kerja: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      Tahun_Kegiatan: '2026',
      Kode_Kegiatan: 'KGT-008',
      Nama_Pegawai: 'Hendra Wijaya',
      NIP_Pegawai: '198712012009011007',
      Pangkat_dan_Golongan: 'Penata Tingkat I (III/d)',
      Jabatan_Pegawai: 'Kepala Seksi Pelaporan',
      Tingkat_Menurut_Peraturan: 'Luar Kota',
      Maksud_Perjalanan_Dinas: 'Pelaporan Keuangan Triwulan',
      Berangkat_dari: 'Kantor Pusat',
      Tujuan: 'Kantor BPK',
      Tanggal_Berangkat: admin.firestore.Timestamp.fromDate(new Date('2026-08-10')),
      Tanggal_Kembali: admin.firestore.Timestamp.fromDate(new Date('2026-08-11')),
      Pada_tanggal: admin.firestore.Timestamp.fromDate(new Date('2026-08-05')),
      Kegiatan: 'Audit',
      Kategori_DL: 'Pendek',
      Alat_Angkutan: 'Kereta Api',
      Nama_Produsen: 'Anisa anggun Fadelia',
      Jabatan_Produsen: 'Analis Keuangan',
      NIP_Produsen: '199001012015032001',
      Nomor_SPT: 'SPT/2026/008',
      No_Urut_SPPD: 8,
      Bulan_Kegiatan: 'VIII',
      Jumlah_Uang: 3500000,
      Terbilang: 'Tiga Juta Lima Ratus Ribu Rupiah',
      wilayah_kerja: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      Tahun_Kegiatan: '2026',
      Kode_Kegiatan: 'KGT-009',
      Nama_Pegawai: 'Indah Permata',
      NIP_Pegawai: '199408152021032008',
      Pangkat_dan_Golongan: 'Penata Muda (III/a)',
      Jabatan_Pegawai: 'Verifikator Keuangan',
      Tingkat_Menurut_Peraturan: 'Luar Kota',
      Maksud_Perjalanan_Dinas: 'Verifikasi SPM',
      Berangkat_dari: 'Kantor Pusat',
      Tujuan: 'Kantor Kas Daerah',
      Tanggal_Berangkat: admin.firestore.Timestamp.fromDate(new Date('2026-09-15')),
      Tanggal_Kembali: admin.firestore.Timestamp.fromDate(new Date('2026-09-15')),
      Pada_tanggal: admin.firestore.Timestamp.fromDate(new Date('2026-09-10')),
      Kegiatan: 'Verifikasi',
      Kategori_DL: 'Pendek',
      Alat_Angkutan: 'Mobil Dinas',
      Nama_Produsen: 'Budi Santoso',
      Jabatan_Produsen: 'Kepala Bidang Keuangan',
      NIP_Produsen: '198501012010011001',
      Nomor_SPT: 'SPT/2026/009',
      No_Urut_SPPD: 9,
      Bulan_Kegiatan: 'IX',
      Jumlah_Uang: 1200000,
      Terbilang: 'Satu Juta Dua Ratus Ribu Rupiah',
      wilayah_kerja: 2,
      createdAt: now,
      updatedAt: now,
    },
    {
      Tahun_Kegiatan: '2026',
      Kode_Kegiatan: 'KGT-010',
      Nama_Pegawai: 'Joko Susilo',
      NIP_Pegawai: '198205201988031009',
      Pangkat_dan_Golongan: 'Pembina Tingkat I (IV/b)',
      Jabatan_Pegawai: 'Sekretaris Daerah',
      Tingkat_Menurut_Peraturan: 'Luar Kota',
      Maksud_Perjalanan_Dinas: 'Koordinasi Pembangunan Daerah',
      Berangkat_dari: 'Kantor Pusat',
      Tujuan: 'Kementerian Dalam Negeri',
      Tanggal_Berangkat: admin.firestore.Timestamp.fromDate(new Date('2026-10-20')),
      Tanggal_Kembali: admin.firestore.Timestamp.fromDate(new Date('2026-10-22')),
      Pada_tanggal: admin.firestore.Timestamp.fromDate(new Date('2026-10-15')),
      Kegiatan: 'Rapat',
      Kategori_DL: 'Sedang',
      Alat_Angkutan: 'Pesawat',
      Nama_Produsen: 'Anisa anggun Fadelia',
      Jabatan_Produsen: 'Analis Keuangan',
      NIP_Produsen: '199001012015032001',
      Nomor_SPT: 'SPT/2026/010',
      No_Urut_SPPD: 10,
      Bulan_Kegiatan: 'X',
      Jumlah_Uang: 8000000,
      Terbilang: 'Delapan Juta Rupiah',
      wilayah_kerja: 2,
      createdAt: now,
      updatedAt: now,
    },
  ];

  const batch = db.batch();
  const collection = db.collection('Data_Primer');
  
  for (const item of data) {
    const docRef = collection.doc();
    batch.set(docRef, item);
    console.log('Prepared to add:', item.Kode_Kegiatan, item.Nama_Pegawai);
  }

  await batch.commit();
  console.log('Seeding Data Primer for wilayah_kerja 2 complete. Added 10 records.');
}

seed().catch(console.error).finally(() => process.exit(0));
